const tableData = [
  {
    productName: "Product 1",
    category: "Category 1",
    sellingPrice: "3232",
    costPrice: "12",
    quantityInStock: "8",
    orderType: "Type 1",
    discountEnabled: true,
    unitPrice: 3232,
    expiryEnabled: true,
    returnPolicy: false,
    shortDescription: "Description 1",
    longDescription: "Long Description 1",
    action: "publish",
    productImage: {
      name: "Image1.svg",
      size: 76051,
      type: "image/svg+xml",
    },
    date: "2024-11-07",
    time: "12:00 PM",
    action: "publish",
    totalValue: 25856,
    status: "Active",
  },
  {
    productName: "Product 2",
    category: "Category 2",
    sellingPrice: "1500",
    costPrice: "10",
    quantityInStock: "15",
    orderType: "Type 2",
    discountEnabled: false,
    unitPrice: 1500,
    expiryEnabled: false,
    returnPolicy: true,
    shortDescription: "Description 2",
    longDescription: "Long Description 2",
    action: "publish",
    productImage: {
      name: "Image2.svg",
      size: 60000,
      type: "image/svg+xml",
    },
    date: "2024-11-07",
    time: "2:00 PM",
    action: "publish",
    totalValue: 25856,
    status: "Active",
  },
  {
    productName: "iPhone 13 Pro",
    category: "Gadgets",
    sellingPrice: 1225000,
    costPrice: 0.0,
    quantityInStock: 8,
    orderType: "Online",
    discountEnabled: true,
    unitPrice: 3232,
    expiryEnabled: true,
    returnPolicy: true,
    shortDescription: "Latest model with advanced features",
    longDescription:
      "The iPhone 13 Pro features a stunning display, powerful processor, and advanced camera system.",
    action: "publish",
    productImage: { name: "iphone13pro.jpg", size: 2048, type: "image/jpeg" },
    date: "2024-11-07",
    time: "12:00 PM",
    action: "publish",
    totalValue: 25856,
    status: "Active",
  },
  {
    productName: "iPhone 12 Pro",
    category: "Gadgets",
    sellingPrice: 725000,
    costPrice: 0.0,
    quantityInStock: 12,
    orderType: "In-store",
    discountEnabled: true,
    unitPrice: 3232,
    expiryEnabled: true,
    returnPolicy: true,
    shortDescription: "Premium smartphone with exceptional camera",
    longDescription:
      "The iPhone 12 Pro delivers great performance and camera quality at a lower price.",
    action: "publish",
    productImage: { name: "iphone12pro.jpg", size: 2048, type: "image/jpeg" },
    date: "2024-11-07",
    time: "12:00 PM",
    action: "publish",
    totalValue: 25856,
    status: "Active",
  },
  {
    productName: "Polo T-Shirt",
    category: "Fashion",
    sellingPrice: 125000,
    costPrice: 0.0,
    quantityInStock: 120,
    orderType: "In-store",
    discountEnabled: false,
    unitPrice: 3232,
    expiryEnabled: false,
    returnPolicy: true,
    shortDescription: "Comfortable and stylish",
    longDescription:
      "This Polo T-Shirt is made from high-quality materials and offers a comfortable fit.",
    action: "publish",
    productImage: { name: "polo_tshirt.jpg", size: 1024, type: "image/jpeg" },
    date: "2024-11-07",
    time: "12:00 PM",
    action: "publish",
    totalValue: 25856,
    status: "Active",
  },
  {
    productName: "Polo T-Shirt",
    category: "Fashion",
    sellingPrice: 125000,
    costPrice: 0.0,
    quantityInStock: "Out of Stock",
    orderType: "In-store",
    discountEnabled: false,
    unitPrice: 3232,
    expiryEnabled: false,
    returnPolicy: true,
    shortDescription: "Comfortable and stylish",
    longDescription:
      "This Polo T-Shirt is made from high-quality materials and offers a comfortable fit.",
    action: "publish",
    productImage: { name: "polo_tshirt.jpg", size: 1024, type: "image/jpeg" },
    date: "2024-11-07",
    time: "12:00 PM",
    action: "publish",
    totalValue: 25856,
    status: "Active",
  },
  {
    productName: "Polo T-Shirt",
    category: "Fashion",
    sellingPrice: 125000,
    costPrice: 0.0,
    quantityInStock: "Out of Stock",
    orderType: "In-store",
    discountEnabled: false,
    unitPrice: 3232,
    expiryEnabled: false,
    returnPolicy: true,
    shortDescription: "Comfortable and stylish",
    longDescription:
      "This Polo T-Shirt is made from high-quality materials and offers a comfortable fit.",
    action: "publish",
    productImage: { name: "polo_tshirt.jpg", size: 1024, type: "image/jpeg" },
    date: "2024-11-07",
    time: "12:00 PM",
    action: "publish",
    totalValue: 25856,
    status: "Active",
  },
];
